# Based on:
# https://github.com/josephwright/siunitx/blob/main/.github/workflows/main.yaml
# https://github.com/zauguin/install-texlive
# https://github.com/moewew/biblatex-ext/blob/dev/.github/workflows/l3build.yml
# https://github.com/CTeX-org/ctex-kit/blob/master/.github/workflows/test.yml
# See also:
# https://github.com/gusbrs/zref-clever/issues/20
# https://github.com/gusbrs/zref-clever/pull/15

name: CI l3build tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 5" # Every Friday at 12:00 UTC

env:
  ZC_PACKAGE_LIST: |
    # The test framework
    l3build
    # Build formats
    latex
    latex-bin
    luatex
    luatexbase
    xetex
    # Fonts
    metafont
    mfware
    ec
    amsfonts
    mathpazo
    psnfss
    tex-gyre
    inconsolata
    # Dependencies
    alphalph
    amsmath
    babel-english
    booktabs
    colortbl
    csquotes
    dvips
    enumitem
    etexcmds
    fancyvrb
    graphics
    hologo
    hypdoc
    hyperref
    iftex
    infwarerr
    intcalc
    kvdefinekeys
    kvoptions
    kvsetkeys
    listings
    ltxcmds
    makeindex
    microtype
    mptopdf
    oberdiek
    pdftexcmds
    tools
    underscore
    upquote
    xkeyval
    zref
    zref-check
    zref-clever

jobs:
  check:
    name: Regression tests and Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: ${{ env.ZC_PACKAGE_LIST }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests and docs
        run: l3build ctan -q

      - name: Archive logs and diffs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-diff-files
          path: |
            build/test*/*.diff
            build/test*/*.log
            build/doc/*.log
          retention-days: 5
